### ISSUE TITLE
2.0 milestone and release

### ISSUE THREAD

**Issue by zxqfox** [bem/bem-history#25]
What you think about releasing v2 branch under version 2.0?
What we need to do before that?
It's like 32 commits after v1.2.

**Comment by tadatuta** [comment]
current state of `v2` branch is stable and ready to use.
the only reason why we still waiting is that we can't get to agreement about versioning. we have quite a few users of the code from `master`, some — from `v1` and some — from `v2`.
all the branches and absolutely incompatible and still in support. so in case we release code from current `v1` branch as `v2.0.0` version and `v2` branch as `v3.0.0` we won't be able to do major updates in `v1` branch if we want to follow semver.

my own POW is not to release `v1` code at all but unfortunately there are users who need it.
