### ISSUE TITLE
Опечатка в описании блока uri на bem.info

### ISSUE THREAD

**Issue by georg-malahov** [bem/bem-history#38]
В описании блока на сайте [bem-info](https://ru.bem.info/libs/bem-history/v3.1.0/#uri) есть пример установки порта `u.setPort(80);`, но в примере ответа `u.toString();` порт остается 8080.

**Comment by tadatuta** [comment]
@yuriMalakhov Спасибо, исправил в https://github.com/bem/bem-history/commit/93f87065155e2ddd43069b6a4b9df1fdfdc97621

**Comment by georg-malahov** [comment]
@tadatuta Спасибо!
