### ISSUE TITLE
Scheme of library work is not found :(

### ISSUE THREAD

**Issue by egorsmorgunov** [bem/bem-history#56]
Readme.md > Scheme of library work > a > bem-history workflow 
Ссылка битая или схема не нарисована?

**Comment by tadatuta** [comment]
@ololobus, похоже, что схема лежала у тебя в дропбоксе и недавно была удалена?
Может быть её еще можно восстановить?

**Comment by ololobus** [comment]
@tadatuta Нет, файл на месте, просто Дропбокс, видимо, перестал отдавать по старым прямым ссылкам сразу на файл. Теперь есть только ссылка, которая открывается в их интерфейсе https://www.dropbox.com/s/3bs0xlar0dxq450/bem-history_from-browser.svg?dl=0

Ну или вот тот файл, лучше его положить в репу. Я думал, что это давно сделали уже :)
[bem-history_from-browser.svg.zip](https://github.com/bem/bem-history/files/966882/bem-history_from-browser.svg.zip)

**Comment by tadatuta** [comment]
Спасибо!
